language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
before_script:
  - npm install -g istanbul coveralls mocha
  - npm install

after_success:
  - make coveralls
script:
  - npm test
  - make test-cov
